Added image view and toolbar to allow for image download
galasa-dev/extensions pull request #75
Opened 2020-09-08 10:34 UTC by Jimbo4794

Signed-off-by: James Davies <jdavies47@hotmail.co.uk>

2020-09-08 11:04 UTC, Jimbo4794 commented
Can now view and download:
<img width="919" alt="image" src="https://user-images.githubusercontent.com/55880188/92468687-73b33180-f1cb-11ea-9581-c65a5b64cc52.png">

2020-09-09 07:33 UTC, Michael-Baylis requested changes

2020-09-09 07:33 UTC, Michael-Baylis commented on galasa-eclipse-parent/dev.galasa.eclipse/src/dev/galasa/eclipse/ui/run/storedartifacts/ImageView.java
> +				InputStream is = Files.newInputStream(this.cachedPath);
Can't do this on the UI Thread.  if this is pulling from the CouchDB RAS it will lock up the UI thread.

2020-09-09 07:33 UTC, Michael-Baylis commented on galasa-eclipse-parent/dev.galasa.eclipse/src/dev/galasa/eclipse/ui/run/storedartifacts/ImageView.java
> +				InputStream is = Files.newInputStream(this.cachedPath);
you are going to have to pull the image using a Job.

2020-09-09 07:33 UTC, Michael-Baylis commented on galasa-eclipse-parent/dev.galasa.eclipse/src/dev/galasa/eclipse/ui/run/storedartifacts/ImageView.java
> +		Path workspace = Paths.get(ResourcesPlugin.getWorkspace().getRoot().getLocation().toString())
is this asking the user where to save the image?

2020-09-30 07:58 UTC, Michael-Baylis commented
rerun tests

2020-09-30 08:54 UTC, merged